import type { MarketplaceSeedData } from './domain';

const now = new Date('2026-03-29T12:00:00.000Z');
const hoursFromNow = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const marketplaceSeed: MarketplaceSeedData = {
    users: [
        {
            id: 'user-ana',
            fullName: 'Ana Mercado',
            email: 'ana@encuentralotodo.app',
            role: 'USER',
            avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
        },
        {
            id: 'admin-luis',
            fullName: 'Luis Admin',
            email: 'luis@encuentralotodo.app',
            role: 'ADMIN',
            avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        },
        {
            id: 'owner-sofia',
            fullName: 'Sofia Rivas',
            email: 'sofia@encuentralotodo.app',
            role: 'USER',
            avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
        },
        {
            id: 'manager-carlos',
            fullName: 'Carlos Mena',
            email: 'carlos@encuentralotodo.app',
            role: 'USER',
            avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
        },
        {
            id: 'manager-julia',
            fullName: 'Julia Herrera',
            email: 'julia@encuentralotodo.app',
            role: 'USER',
            avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        },
        {
            id: 'manager-elena',
            fullName: 'Elena Pichardo',
            email: 'elena@encuentralotodo.app',
            role: 'USER',
            avatarUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=200&q=80',
        },
        {
            id: 'owner-mateo',
            fullName: 'Mateo Cordero',
            email: 'mateo@encuentralotodo.app',
            role: 'USER',
            avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        },
        {
            id: 'owner-lucia',
            fullName: 'Lucia Peña',
            email: 'lucia@encuentralotodo.app',
            role: 'USER',
            avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
        },
    ],
    businesses: [
        {
            id: 'biz-casa-norte',
            name: 'Casa Norte Market',
            description: 'Tienda general con abarrotes, snacks, productos de limpieza y entregas rápidas dentro de la zona norte.',
            category: 'GENERAL_STORE',
            location: {
                lat: 18.4861,
                lng: -69.9312,
                zone: 'Zona Norte',
                address: 'Av. Charles Summer 42, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'PREMIUM_PLUS',
            ownerId: 'owner-sofia',
            managers: ['manager-carlos', 'manager-julia'],
            status: 'APPROVED',
            whatsappNumber: '18095550101',
            promoBadge: 'Envío en 30 min',
            lastUpdated: hoursFromNow(-4),
        },
        {
            id: 'biz-sabor-urbano',
            name: 'Sabor Urbano',
            description: 'Cocina casual con bowls, wraps y combos ejecutivos para almuerzo con recogida o delivery por WhatsApp.',
            category: 'RESTAURANT',
            location: {
                lat: 18.4702,
                lng: -69.9078,
                zone: 'Naco',
                address: 'Calle Fantino Falco 11, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'PREMIUM',
            ownerId: 'owner-sofia',
            managers: ['manager-carlos'],
            status: 'APPROVED',
            whatsappNumber: '18095550102',
            promoBadge: 'Combo del día',
            lastUpdated: hoursFromNow(-12),
        },
        {
            id: 'biz-barrio-fit',
            name: 'Barrio Fit Studio',
            description: 'Estudio boutique con clases funcionales, asesoría nutricional y paquetes corporativos gestionados desde WhatsApp.',
            category: 'SERVICE',
            location: {
                lat: 18.4745,
                lng: -69.8881,
                zone: 'Piantini',
                address: 'Calle Federico Geraldino 88, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'PREMIUM_PLUS',
            ownerId: 'owner-sofia',
            managers: ['manager-julia'],
            status: 'APPROVED',
            whatsappNumber: '18095550104',
            promoBadge: 'Clases trial',
            lastUpdated: hoursFromNow(-20),
        },
        {
            id: 'biz-cafe-ruta-12',
            name: 'Cafe Ruta 12',
            description: 'Cafetería urbana con brunch, panadería artesanal y pedidos recurrentes para oficinas cercanas.',
            category: 'RESTAURANT',
            location: {
                lat: 18.4669,
                lng: -69.9423,
                zone: 'Evaristo Morales',
                address: 'Calle Rafael Augusto Sanchez 12, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'PREMIUM',
            ownerId: 'owner-sofia',
            managers: ['manager-carlos', 'manager-julia'],
            status: 'APPROVED',
            whatsappNumber: '18095550105',
            promoBadge: 'Brunch express',
            lastUpdated: hoursFromNow(-28),
        },
        {
            id: 'biz-estudio-aura',
            name: 'Estudio Aura Print',
            description: 'Diseño e impresión rápida para branding, menús, stickers y piezas promocionales para negocios locales.',
            category: 'SERVICE',
            location: {
                lat: 18.4623,
                lng: -69.9145,
                zone: 'Gazcue',
                address: 'Av. Independencia 170, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'PREMIUM_PLUS',
            ownerId: 'owner-mateo',
            managers: ['manager-elena'],
            status: 'APPROVED',
            whatsappNumber: '18095550106',
            promoBadge: 'Entrega same-day',
            lastUpdated: hoursFromNow(-36),
        },
        {
            id: 'biz-mercado-colonial',
            name: 'Mercado Colonial Express',
            description: 'Mini market enfocado en snacks, bebidas frías y canastas rápidas para la zona colonial y alrededores.',
            category: 'GENERAL_STORE',
            location: {
                lat: 18.4717,
                lng: -69.8859,
                zone: 'Zona Colonial',
                address: 'Calle El Conde 52, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'PREMIUM',
            ownerId: 'owner-sofia',
            managers: ['manager-julia'],
            status: 'PENDING',
            whatsappNumber: '18095550107',
            promoBadge: 'Canastas rápidas',
            lastUpdated: hoursFromNow(-6),
        },
        {
            id: 'biz-fixit-pro',
            name: 'FixIt Pro Servicios',
            description: 'Servicios técnicos a domicilio para electrodomésticos, instalaciones y mantenimiento preventivo.',
            category: 'SERVICE',
            location: {
                lat: 18.4567,
                lng: -69.9524,
                zone: 'Bella Vista',
                address: 'Av. Sarasota 101, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'FREE_TRIAL',
            ownerId: 'user-ana',
            managers: ['manager-elena'],
            status: 'PENDING',
            whatsappNumber: '18095550103',
            promoBadge: 'Diagnóstico inicial',
            lastUpdated: hoursFromNow(-2),
        },
        {
            id: 'biz-cocina-central',
            name: 'Cocina Central RD',
            description: 'Kitchen de producción para almuerzos corporativos, bandejas compartidas y menús semanales por suscripción.',
            category: 'RESTAURANT',
            location: {
                lat: 18.4431,
                lng: -69.9642,
                zone: 'Mirador Sur',
                address: 'Av. Anacaona 24, Santo Domingo',
            },
            images: {
                profile: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80',
                banner: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=1400&q=80',
            },
            subscriptionType: 'PREMIUM_PLUS',
            ownerId: 'owner-lucia',
            managers: ['manager-elena'],
            status: 'APPROVED',
            whatsappNumber: '18095550108',
            promoBadge: 'Catering semanal',
            lastUpdated: hoursFromNow(-44),
        },
    ],
    products: [
        {
            id: 'prod-cereal',
            businessId: 'biz-casa-norte',
            name: 'Pack familiar de cereales',
            description: 'Selección variada de cereales y granolas para consumo semanal.',
            images: [
                'https://images.unsplash.com/photo-1515543904379-3d757afe72e2?auto=format&fit=crop&w=800&q=80',
            ],
            price: 12.5,
            isFeatured: true,
            lastUpdated: hoursFromNow(-10),
        },
        {
            id: 'prod-limpieza',
            businessId: 'biz-casa-norte',
            name: 'Kit limpieza hogar',
            description: 'Combo con detergente, cloro y multiusos para reposición semanal.',
            images: [
                'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=800&q=80',
            ],
            price: 19.9,
            isFeatured: true,
            lastUpdated: hoursFromNow(-11),
        },
        {
            id: 'prod-despensa',
            businessId: 'biz-casa-norte',
            name: 'Caja despensa oficina',
            description: 'Selección mensual de snacks, café instantáneo y bebidas para equipos pequeños.',
            images: [
                'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=800&q=80',
                'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?auto=format&fit=crop&w=800&q=80',
            ],
            price: 29.5,
            isFeatured: true,
            lastUpdated: hoursFromNow(-18),
        },
        {
            id: 'prod-soda-pack',
            businessId: 'biz-casa-norte',
            name: 'Pack bebidas frías',
            description: 'Bebidas surtidas para reuniones rápidas con entrega el mismo día.',
            images: [
                'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
            ],
            price: 14.25,
            isFeatured: false,
            lastUpdated: hoursFromNow(-30),
        },
        {
            id: 'prod-office-snacks',
            businessId: 'biz-casa-norte',
            name: 'Snack station refill',
            description: 'Reposición completa para estaciones de snack en oficinas medianas.',
            images: [
                'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80',
            ],
            price: 35.75,
            isFeatured: false,
            lastUpdated: hoursFromNow(-32),
        },
        {
            id: 'prod-bowl',
            businessId: 'biz-sabor-urbano',
            name: 'Bowl criollo grill',
            description: 'Arroz, proteína a la plancha, vegetales y salsa de la casa.',
            images: [
                'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
            ],
            price: 8.9,
            isFeatured: true,
            lastUpdated: hoursFromNow(-16),
        },
        {
            id: 'prod-wrap',
            businessId: 'biz-sabor-urbano',
            name: 'Wrap spicy chicken',
            description: 'Wrap con pollo sazonado, lechuga fresca y aderezo de cilantro.',
            images: [
                'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
            ],
            price: 7.5,
            isFeatured: false,
            lastUpdated: hoursFromNow(-18),
        },
        {
            id: 'prod-combo-proteina',
            businessId: 'biz-sabor-urbano',
            name: 'Combo proteína doble',
            description: 'Bowl con doble proteína, topping premium y bebida incluida.',
            images: [
                'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
            ],
            price: 12.25,
            isFeatured: true,
            lastUpdated: hoursFromNow(-24),
        },
        {
            id: 'prod-wrap-veggie',
            businessId: 'biz-sabor-urbano',
            name: 'Wrap veggie grill',
            description: 'Wrap vegetariano con vegetales grillados y hummus de la casa.',
            images: [
                'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?auto=format&fit=crop&w=800&q=80',
            ],
            price: 7.1,
            isFeatured: false,
            lastUpdated: hoursFromNow(-40),
        },
        {
            id: 'prod-diagnostico',
            businessId: 'biz-fixit-pro',
            name: 'Diagnóstico de lavadora',
            description: 'Revisión técnica con presupuesto enviado por WhatsApp.',
            images: [
                'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',
            ],
            price: 15,
            isFeatured: true,
            lastUpdated: hoursFromNow(-3),
        },
        {
            id: 'prod-reparacion-ac',
            businessId: 'biz-fixit-pro',
            name: 'Mantenimiento de aire inverter',
            description: 'Limpieza profunda y revisión preventiva para equipos residenciales.',
            images: [
                'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
            ],
            price: 42,
            isFeatured: true,
            lastUpdated: hoursFromNow(-5),
        },
        {
            id: 'prod-funcional-pass',
            businessId: 'biz-barrio-fit',
            name: 'Pase funcional semanal',
            description: 'Acceso de 7 días con clases ilimitadas y evaluación inicial.',
            images: [
                'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            price: 24,
            isFeatured: true,
            lastUpdated: hoursFromNow(-21),
        },
        {
            id: 'prod-nutricion-express',
            businessId: 'biz-barrio-fit',
            name: 'Consulta nutricional express',
            description: 'Sesión de 30 minutos con guía de objetivos y plan base.',
            images: [
                'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80',
            ],
            price: 18,
            isFeatured: false,
            lastUpdated: hoursFromNow(-26),
        },
        {
            id: 'prod-pilates-pack',
            businessId: 'biz-barrio-fit',
            name: 'Pack de pilates 8 sesiones',
            description: 'Paquete mensual con sesiones mat y seguimiento de progreso.',
            images: [
                'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
            ],
            price: 58,
            isFeatured: true,
            lastUpdated: hoursFromNow(-34),
        },
        {
            id: 'prod-croissant-box',
            businessId: 'biz-cafe-ruta-12',
            name: 'Croissant box oficina',
            description: 'Caja surtida de croissants dulces y salados para reuniones matutinas.',
            images: [
                'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
            ],
            price: 21.5,
            isFeatured: true,
            lastUpdated: hoursFromNow(-14),
        },
        {
            id: 'prod-brunch-duo',
            businessId: 'biz-cafe-ruta-12',
            name: 'Brunch duo',
            description: 'Dos platos brunch con café de especialidad y jugos naturales.',
            images: [
                'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=800&q=80',
            ],
            price: 17.9,
            isFeatured: true,
            lastUpdated: hoursFromNow(-19),
        },
        {
            id: 'prod-sticker-pack',
            businessId: 'biz-estudio-aura',
            name: 'Sticker pack comercial',
            description: 'Lote de stickers laminados para branding de empaques y vitrinas.',
            images: [
                'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
            ],
            price: 32,
            isFeatured: true,
            lastUpdated: hoursFromNow(-22),
        },
        {
            id: 'prod-menu-board',
            businessId: 'biz-estudio-aura',
            name: 'Menu board express',
            description: 'Diseño + impresión de menú rígido para restaurantes y cafés.',
            images: [
                'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=800&q=80',
            ],
            price: 44,
            isFeatured: false,
            lastUpdated: hoursFromNow(-38),
        },
        {
            id: 'prod-canasta-colonial',
            businessId: 'biz-mercado-colonial',
            name: 'Canasta colonial express',
            description: 'Canasta con snacks, bebidas y básicos para estadías cortas o Airbnb.',
            images: [
                'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
            ],
            price: 28,
            isFeatured: true,
            lastUpdated: hoursFromNow(-7),
        },
        {
            id: 'prod-bandeja-ejecutiva',
            businessId: 'biz-cocina-central',
            name: 'Bandeja ejecutiva 10 pax',
            description: 'Menú corporativo para reuniones de equipo con montaje básico incluido.',
            images: [
                'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=800&q=80',
            ],
            price: 68,
            isFeatured: true,
            lastUpdated: hoursFromNow(-23),
        },
        {
            id: 'prod-menu-semanal',
            businessId: 'biz-cocina-central',
            name: 'Plan semanal corporativo',
            description: 'Servicio recurrente con menú rotativo para equipos pequeños y medianos.',
            images: [
                'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
            ],
            price: 120,
            isFeatured: false,
            lastUpdated: hoursFromNow(-31),
        },
    ],
    promotions: [
        {
            id: 'promo-casa-norte',
            businessId: 'biz-casa-norte',
            title: '2x1 en snacks seleccionados',
            description: 'Promoción válida para marcas participantes hasta agotar existencias.',
            promoPrice: 4.99,
            originalPrice: 9.98,
            validUntil: daysFromNow(14),
            image: 'https://images.unsplash.com/photo-1604719312566-8912e9c8a213?auto=format&fit=crop&w=900&q=80',
            lastUpdated: hoursFromNow(-10),
        },
        {
            id: 'promo-sabor-urbano',
            businessId: 'biz-sabor-urbano',
            title: 'Combo ejecutivo express',
            description: 'Bowl más bebida por tiempo limitado entre 12 PM y 3 PM.',
            promoPrice: 10.5,
            originalPrice: 13.9,
            validUntil: daysFromNow(7),
            image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80',
            lastUpdated: hoursFromNow(-13),
        },
        {
            id: 'promo-barrio-fit',
            businessId: 'biz-barrio-fit',
            title: 'Semana trial + evaluación',
            description: 'Pase de 7 días con evaluación física inicial incluida para nuevos clientes.',
            promoPrice: 19,
            originalPrice: 28,
            validUntil: daysFromNow(10),
            image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80',
            lastUpdated: hoursFromNow(-18),
        },
        {
            id: 'promo-cafe-ruta',
            businessId: 'biz-cafe-ruta-12',
            title: 'Brunch office bundle',
            description: 'Box para reuniones de mañana con café filtrado y piezas surtidas.',
            promoPrice: 26,
            originalPrice: 34,
            validUntil: daysFromNow(6),
            image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80',
            lastUpdated: hoursFromNow(-20),
        },
        {
            id: 'promo-aura-print',
            businessId: 'biz-estudio-aura',
            title: 'Starter kit branding',
            description: 'Diseño de logo adaptado + sticker pack para nuevos negocios.',
            promoPrice: 59,
            originalPrice: 82,
            validUntil: daysFromNow(18),
            image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
            lastUpdated: hoursFromNow(-26),
        },
        {
            id: 'promo-cocina-central',
            businessId: 'biz-cocina-central',
            title: 'Catering 15 pax launch',
            description: 'Precio especial de lanzamiento para pedidos corporativos pequeños.',
            promoPrice: 89,
            originalPrice: 115,
            validUntil: daysFromNow(12),
            image: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=900&q=80',
            lastUpdated: hoursFromNow(-30),
        },
    ],
    reviews: [
        {
            id: 'review-1',
            rating: 5,
            comment: 'Pedido rápido y atención muy clara por WhatsApp.',
            userId: 'user-ana',
            businessId: 'biz-casa-norte',
            createdAt: daysAgo(9),
        },
        {
            id: 'review-2',
            rating: 4,
            comment: 'El combo llegó bien presentado y a buen precio.',
            userId: 'manager-carlos',
            businessId: 'biz-sabor-urbano',
            createdAt: daysAgo(7),
        },
        {
            id: 'review-3',
            rating: 5,
            comment: 'Muy responsables con la visita técnica y el seguimiento.',
            userId: 'owner-sofia',
            businessId: 'biz-fixit-pro',
            createdAt: daysAgo(5),
        },
        {
            id: 'review-4',
            rating: 5,
            comment: 'Excelente surtido y muy buen seguimiento para pedidos recurrentes.',
            userId: 'owner-lucia',
            businessId: 'biz-casa-norte',
            createdAt: daysAgo(4),
        },
        {
            id: 'review-5',
            rating: 4,
            comment: 'El bowl llegó caliente y la promo sí coincidía con lo publicado.',
            userId: 'manager-julia',
            businessId: 'biz-sabor-urbano',
            createdAt: daysAgo(3),
        },
        {
            id: 'review-6',
            rating: 5,
            comment: 'El estudio mantiene muy buen ritmo y la prueba inicial estuvo muy bien guiada.',
            userId: 'user-ana',
            businessId: 'biz-barrio-fit',
            createdAt: daysAgo(6),
        },
        {
            id: 'review-7',
            rating: 4,
            comment: 'Nos resolvieron la impresión del menú el mismo día.',
            userId: 'owner-sofia',
            businessId: 'biz-estudio-aura',
            createdAt: daysAgo(8),
        },
        {
            id: 'review-8',
            rating: 5,
            comment: 'Muy buen café y el box de brunch llegó perfecto para la reunión.',
            userId: 'manager-elena',
            businessId: 'biz-cafe-ruta-12',
            createdAt: daysAgo(2),
        },
        {
            id: 'review-9',
            rating: 5,
            comment: 'El catering semanal simplificó bastante la operación del equipo.',
            userId: 'admin-luis',
            businessId: 'biz-cocina-central',
            createdAt: daysAgo(5),
        },
        {
            id: 'review-10',
            rating: 4,
            comment: 'Buen empaquetado y atención rápida para un pedido de último minuto.',
            userId: 'owner-mateo',
            businessId: 'biz-casa-norte',
            createdAt: daysAgo(1),
        },
        {
            id: 'review-11',
            rating: 5,
            comment: 'Muy útil para clases corporativas, con coordinación clara por WhatsApp.',
            userId: 'owner-lucia',
            businessId: 'biz-barrio-fit',
            createdAt: daysAgo(10),
        },
        {
            id: 'review-12',
            rating: 4,
            comment: 'La asesoría de branding fue ágil y con entregables claros.',
            userId: 'manager-carlos',
            businessId: 'biz-estudio-aura',
            createdAt: daysAgo(11),
        },
    ],
};

export function cloneMarketplaceSeed(): MarketplaceSeedData {
    return JSON.parse(JSON.stringify(marketplaceSeed)) as MarketplaceSeedData;
}